chain:
  blockchain: BLOCKCHAIN_TEMPO
  network: NETWORK_TEMPO_MAINNET
config_name: tempo-mainnet
sla:
  tier: 1
table:
  supported_formats:
    - native
    - rosetta
server:
  bind_address: ":9090"
