chain:
  blockchain: BLOCKCHAIN_ABSTRACT
  network: NETWORK_ABSTRACT_MAINNET
config_name: abstract-mainnet
sla:
  tier: 1
table:
  supported_formats:
    - native
    - rosetta
server:
  bind_address: ":9090"

