chain:
  blockchain: BLOCKCHAIN_BITCOINCASH
  network: NETWORK_BITCOINCASH_MAINNET
config_name: bitcoincash-mainnet
sla:
  tier: 1
table:
  supported_formats:
    - native
server:
  bind_address: ":9090"
