chain:
  blockchain: BLOCKCHAIN_MEGAETH
  network: NETWORK_MEGAETH_MAINNET
config_name: megaeth-mainnet
sla:
  tier: 1
table:
  supported_formats:
    - native
    - rosetta
server:
  bind_address: ":9090"

